import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { backgroundColor: "#f7f2e8", padding: "40 50", fontFamily: "Helvetica" },
  header: { marginBottom: 24 },
  logo: { fontSize: 9, color: "#c9a24a", letterSpacing: 3, textTransform: "uppercase" },
  title: { fontSize: 18, color: "#1b3a2a", fontFamily: "Helvetica-Bold", marginTop: 6 },
  date: { fontSize: 11, color: "#1a1a1860", marginTop: 4 },
  divider: { borderBottom: "1 solid #e8e3d8", marginVertical: 16 },
  tableHeader: { flexDirection: "row", backgroundColor: "#1b3a2a1a", padding: "6 10", borderRadius: 4, marginBottom: 4 },
  colLabel: { fontSize: 7, color: "#1a1a1880", textTransform: "uppercase", letterSpacing: 1.5, fontFamily: "Helvetica-Bold" },
  row: { flexDirection: "row", padding: "7 10", borderBottom: "1 solid #e8e3d800" },
  rowAlt: { backgroundColor: "#1b3a2a06" },
  cell: { fontSize: 9, color: "#1a1a18", flex: 1 },
  badge: { fontSize: 7, color: "#1a1a1870", paddingHorizontal: 4, paddingVertical: 2, backgroundColor: "#1a1a180a", borderRadius: 3 },
  present: { fontSize: 7, color: "#166534", backgroundColor: "#dcfce7", paddingHorizontal: 4, paddingVertical: 2, borderRadius: 3 },
  absent: { fontSize: 7, color: "#1a1a1870", paddingHorizontal: 4, paddingVertical: 2, borderRadius: 3 },
  footer: { marginTop: "auto", paddingTop: 16, borderTop: "1 solid #e8e3d8", fontSize: 8, color: "#1a1a1850", textAlign: "center" },
});

interface ExportPdfProps {
  eventTitle: string;
  eventDate:  string;
  registrants: Array<{
    first_name: string;
    last_name:  string;
    email:      string | null;
    phone:      string | null;
    role:       string;
    checked_in: boolean;
  }>;
}

export function ExportPdf({ eventTitle, eventDate, registrants }: ExportPdfProps) {
  return (
    <Document title={`Registrants — ${eventTitle}`} author="The Green House">
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.logo}>The Green House</Text>
          <Text style={styles.title}>{eventTitle}</Text>
          <Text style={styles.date}>{eventDate} · {registrants.length} registrants</Text>
        </View>

        <View style={styles.divider} />

        <View style={styles.tableHeader}>
          <Text style={[styles.colLabel, { flex: 2 }]}>Name</Text>
          <Text style={[styles.colLabel, { flex: 2 }]}>Contact</Text>
          <Text style={[styles.colLabel, { flex: 1 }]}>Role</Text>
          <Text style={[styles.colLabel, { flex: 1 }]}>Attended</Text>
        </View>

        {registrants.map((r, i) => (
          <View key={i} style={[styles.row, i % 2 !== 0 ? styles.rowAlt : {}]}>
            <Text style={[styles.cell, { flex: 2 }]}>{r.first_name} {r.last_name}</Text>
            <Text style={[styles.cell, { flex: 2, color: "#1a1a1870" }]}>{r.email ?? r.phone ?? "—"}</Text>
            <Text style={[styles.cell, { flex: 1 }]}><Text style={styles.badge}>{r.role}</Text></Text>
            <Text style={[styles.cell, { flex: 1 }]}>
              <Text style={r.checked_in ? styles.present : styles.absent}>
                {r.checked_in ? "Yes" : "No"}
              </Text>
            </Text>
          </View>
        ))}

        <View style={styles.footer}>
          <Text>Generated by The Green House Admin · thegreenhouseke.com</Text>
        </View>
      </Page>
    </Document>
  );
}
