import type { Metadata } from "next";
import { Cormorant_Garamond, DM_Sans } from "next/font/google";
import { Toaster } from "sonner";
import { Analytics } from "@vercel/analytics/react";
import { MobileScrollFix } from "@/components/mobile-scroll-fix";
import "./globals.css";
import { cn } from "@/lib/utils";
import { GOOGLE_SITE_VERIFICATION, SOCIAL_INSTAGRAM, SOCIAL_TIKTOK, SOCIAL_YOUTUBE, SOCIAL_FACEBOOK, SOCIAL_TWITTER } from "@/lib/constants";

const displayFont = Cormorant_Garamond({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const bodyFont = DM_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

const SITE_BASE = process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.greenhousews.co.ke";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_BASE),
  verification: {
    google: GOOGLE_SITE_VERIFICATION,
  },
  title: {
    // Kept under 60 characters so Google shows it whole rather than truncating.
    default: "The Green House: Worship Community in Nairobi, Kenya",
    template: "%s | The Green House",
  },
  description:
    "A cross-church worship community in Nairobi, Kenya. Quarterly gatherings for worship, prayer, and real connection across churches. Low pressure. Everyone welcome.",
  keywords: [
    "greenhouse worship community nairobi",
    "the green house worship kenya",
    "cross-church worship nairobi",
    "nairobi worship gathering",
    "worship community nairobi kenya",
    "christian community nairobi",
    "worship night nairobi",
    "nairobi church fellowship",
    "worship and prayer nairobi kenya",
    "quarterly worship nairobi",
    "interdenominational worship kenya",
    "nairobi christian gathering",
    "greenhousews",
  ],
  // Icons are intentionally not declared here. Setting this key makes Next
  // use only what is listed and skip its file conventions, which is how the
  // site ended up serving an SVG and nothing else: /favicon.ico returned 404,
  // and Google's favicon crawler wants a raster icon at the root. The files in
  // app/ (favicon.ico, icon.svg, icon.png, apple-icon.png) are detected
  // automatically and emitted with correct types and sizes.
  openGraph: {
    type:     "website",
    locale:   "en_KE",
    siteName: "The Green House Worship Community",
    url:      SITE_BASE,
    images:   [{ url: "/opengraph-image", width: 1200, height: 630, alt: "Greenhouse Worship Community, Nairobi, Kenya" }],
  },
  twitter: { card: "summary_large_image", images: ["/opengraph-image"] },
  robots:  { index: true, follow: true },
};

const sameAs = [SOCIAL_INSTAGRAM, SOCIAL_TIKTOK, SOCIAL_YOUTUBE, SOCIAL_FACEBOOK, SOCIAL_TWITTER].filter(Boolean);

const orgJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "The Green House Worship Community",
  "alternateName": [
    "Green House Worship Community",
    "The Green House",
    "The Greenhouse Worship Session",
    "Green House Worship Session",
    "greenhousews",
  ],
  "url": SITE_BASE,
  "logo": `${SITE_BASE}/icon.svg`,
  "description": "A cross-church worship community in Nairobi, Kenya. Quarterly gatherings for worship, prayer, and real connection across churches.",
  "foundingDate": "2026",
  "address": {
    "@type": "PostalAddress",
    "addressLocality": "Nairobi",
    "addressRegion": "Nairobi County",
    "addressCountry": "KE",
  },
  "areaServed": {
    "@type": "City",
    "name": "Nairobi",
    "sameAs": "https://www.wikidata.org/wiki/Q3870",
  },
  ...(sameAs.length > 0 ? { "sameAs": sameAs } : {}),
};

// Sitelinks (the indented sub-links under a result) are generated by Google
// from site structure and click behaviour. They cannot be requested. What we
// can do is state the site's main sections unambiguously, keep them in the
// header nav, and make sure each one is reachable, indexable and named the
// same way everywhere. That is what these two blocks do.
const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "name": "The Green House Worship Community",
  "alternateName": "The Green House W.S",
  "url": SITE_BASE,
  "inLanguage": "en-KE",
  "publisher": { "@type": "Organization", "name": "The Green House Worship Community", "url": SITE_BASE },
};

const NAV_SECTIONS = [
  { name: "About",        path: "/about" },
  { name: "Sessions",     path: "/events" },
  { name: "Blog",         path: "/blog" },
  { name: "Gallery",      path: "/gallery" },
  { name: "Get Involved", path: "/get-involved" },
];

const navJsonLd = {
  "@context": "https://schema.org",
  "@type": "ItemList",
  "itemListElement": NAV_SECTIONS.map((s, i) => ({
    "@type": "SiteNavigationElement",
    "position": i + 1,
    "name": s.name,
    "url": `${SITE_BASE}${s.path}`,
  })),
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn(displayFont.variable, bodyFont.variable)}>
      <body className="antialiased force-light grain" suppressHydrationWarning>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(navJsonLd) }}
        />
        <MobileScrollFix />
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: "var(--forest)",
              color: "var(--cream)",
              border: "1px solid var(--moss)",
            },
          }}
        />
        <Analytics />
      </body>
    </html>
  );
}
